-- Read-only metadata inventory for the existing DEV installation.
-- SHOW results are limited by the active role's visibility.
-- No grants, inference calls, task execution, or billing changes.
SELECT CURRENT_ACCOUNT() AS ACCOUNT_LOCATOR,
       CURRENT_REGION() AS REGION,
       CURRENT_ROLE() AS ACTIVE_ROLE,
       CURRENT_DATABASE() AS DATABASE_NAME,
       CURRENT_WAREHOUSE() AS WAREHOUSE_NAME;

SHOW TASKS IN SCHEMA TRUST_SIGNAL_DEV.TRUST_SIGNAL_OPS;
SHOW PROCEDURES LIKE '%WORKFLOW%' IN SCHEMA TRUST_SIGNAL_DEV.TRUST_SIGNAL_OPS;
SHOW INTEGRATIONS;
SHOW NETWORK RULES IN SCHEMA TRUST_SIGNAL_DEV.TRUST_SIGNAL_SECRETS;
SHOW WAREHOUSES LIKE 'TRUST_SIGNAL_PIPELINE_WH';
SHOW RESOURCE MONITORS;
SHOW PARAMETERS LIKE 'CORTEX%' IN ACCOUNT;
SHOW PARAMETERS LIKE 'ENABLE_CORTEX%' IN ACCOUNT;
SHOW GRANTS TO ROLE TRUST_SIGNAL_DEPLOYER;
SHOW GRANTS TO ROLE TRUST_SIGNAL_ORCHESTRATOR;
