-- Read-only checks for the development workflow deployment.
USE DATABASE TRUST_SIGNAL_DEV;
SHOW TASKS IN SCHEMA TRUST_SIGNAL_OPS;

SELECT RUN_ID, REQUEST_ID, RUN_STATUS,
       RESULT:identity_status::VARCHAR AS IDENTITY_STATUS,
       RESULT:assessment:score_status::VARCHAR AS SCORE_STATUS,
       RESULT:assessment:disposition::VARCHAR AS DISPOSITION,
       RESULT:assessment:reasons AS REASONS,
       STARTED_AT, COMPLETED_AT
FROM TRUST_SIGNAL_OPS.CASE_RUNS
ORDER BY STARTED_AT DESC;

SELECT RUN_ID, STAGE, ATTEMPT, STAGE_STATUS, ERROR_CATEGORY,
       STARTED_AT, COMPLETED_AT
FROM TRUST_SIGNAL_OPS.STAGE_ATTEMPTS
ORDER BY STARTED_AT DESC;

SELECT NAME, STATE, QUERY_ID, ERROR_CODE, ERROR_MESSAGE
FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY(
    SCHEDULED_TIME_RANGE_START => DATEADD('hour', -24, CURRENT_TIMESTAMP()),
    RESULT_LIMIT => 100))
WHERE DATABASE_NAME = 'TRUST_SIGNAL_DEV'
  AND SCHEMA_NAME = 'TRUST_SIGNAL_OPS'
ORDER BY SCHEDULED_TIME DESC;
