-- Read-only DEV privilege inventory; review identifiers before reuse.
-- DESCRIBE USER includes account metadata: do not publish its raw output.
USE ROLE ACCOUNTADMIN;
SHOW GRANTS TO USER TRUST_SIGNAL_INGEST_SVC;
SHOW GRANTS TO ROLE TRUST_SIGNAL_INGESTOR;
SHOW GRANTS OF ROLE TRUST_SIGNAL_INGESTOR;
SHOW GRANTS TO ROLE PUBLIC;
DESCRIBE USER TRUST_SIGNAL_INGEST_SVC;
SHOW GRANTS TO ROLE SNOWFLAKE_LEARNING_ROLE;
SHOW FUTURE GRANTS TO ROLE PUBLIC;
SHOW FUTURE GRANTS TO ROLE TRUST_SIGNAL_INGESTOR;
SHOW TABLES LIKE 'CASES' IN SCHEMA TRUST_SIGNAL_DEV.TRUST_SIGNAL_CORE;
SHOW WAREHOUSES;

-- Optional, larger inventory: no Cortex execution or inference.
SHOW GRANTS TO DATABASE ROLE SNOWFLAKE.CORTEX_USER;
