-- Resume only the inspected, approved partial deployment.
-- Operator role/grants already exist; do not recreate them.
-- ML_USER is irrevocable and deliberately retained in PUBLIC.
-- DATA_METRIC_USER revocation was also denied under ACCOUNTADMIN in this account.
USE ROLE ACCOUNTADMIN;
REVOKE ROLE SNOWFLAKE_LEARNING_ROLE FROM ROLE PUBLIC;
REVOKE USAGE ON WAREHOUSE "SYSTEM$STREAMLIT_NOTEBOOK_WH" FROM ROLE PUBLIC;
REVOKE USAGE ON COMPUTE POOL SYSTEM_COMPUTE_POOL_CPU FROM ROLE PUBLIC;
REVOKE USAGE ON COMPUTE POOL SYSTEM_COMPUTE_POOL_GPU FROM ROLE PUBLIC;
ALTER USER TRUST_SIGNAL_INGEST_SVC SET DEFAULT_SECONDARY_ROLES = ();
SHOW GRANTS TO ROLE TRUST_SIGNAL_PLATFORM_OPERATOR;
SHOW GRANTS TO ROLE PUBLIC;
SHOW GRANTS TO USER TRUST_SIGNAL_INGEST_SVC;
SHOW TASKS LIKE 'TS_CLAIM' IN SCHEMA TRUST_SIGNAL_DEV.TRUST_SIGNAL_OPS;
