-- Account-specific DEV operation, not application startup or installation DDL.
-- Apply only after explicit approval of the 1-credit daily quota.
-- A rerun deliberately fails if the monitor exists; inspect before altering it.
USE ROLE ACCOUNTADMIN;

CREATE RESOURCE MONITOR TRUST_SIGNAL_DEV_DAILY_RM
    WITH CREDIT_QUOTA = 1
         FREQUENCY = DAILY
         START_TIMESTAMP = IMMEDIATELY
    TRIGGERS ON 50 PERCENT DO NOTIFY
             ON 80 PERCENT DO NOTIFY
             ON 100 PERCENT DO SUSPEND;

ALTER WAREHOUSE TRUST_SIGNAL_PIPELINE_WH SET
    RESOURCE_MONITOR = TRUST_SIGNAL_DEV_DAILY_RM
    ENABLE_QUERY_ACCELERATION = FALSE;

SHOW RESOURCE MONITORS LIKE 'TRUST_SIGNAL_DEV_DAILY_RM';
SHOW WAREHOUSES LIKE 'TRUST_SIGNAL_PIPELINE_WH';
SHOW TASKS LIKE 'TS_CLAIM' IN SCHEMA TRUST_SIGNAL_DEV.TRUST_SIGNAL_OPS;
