-- Reviewed, account-specific DEV change. Requires explicit approval.
-- Preserve selected PUBLIC feature grants for the current human operator first.
-- Do not rerun blindly: CREATE ROLE intentionally refuses an existing role.
USE ROLE ACCOUNTADMIN;
CREATE ROLE TRUST_SIGNAL_PLATFORM_OPERATOR;

GRANT USE AI FUNCTIONS ON ACCOUNT TO ROLE TRUST_SIGNAL_PLATFORM_OPERATOR;
GRANT BIND SERVICE ENDPOINT ON ACCOUNT TO ROLE TRUST_SIGNAL_PLATFORM_OPERATOR;
GRANT EXECUTE AGENT TASK ON ACCOUNT TO ROLE TRUST_SIGNAL_PLATFORM_OPERATOR;
GRANT MANAGE ARTIFACT PUBLICATION ON ACCOUNT TO ROLE TRUST_SIGNAL_PLATFORM_OPERATOR;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE TRUST_SIGNAL_PLATFORM_OPERATOR;
GRANT DATABASE ROLE SNOWFLAKE.COPILOT_USER TO ROLE TRUST_SIGNAL_PLATFORM_OPERATOR;
GRANT DATABASE ROLE SNOWFLAKE.ML_USER TO ROLE TRUST_SIGNAL_PLATFORM_OPERATOR;
GRANT DATABASE ROLE SNOWFLAKE.DATA_METRIC_USER TO ROLE TRUST_SIGNAL_PLATFORM_OPERATOR;
GRANT ROLE SNOWFLAKE_LEARNING_ROLE TO ROLE TRUST_SIGNAL_PLATFORM_OPERATOR;
GRANT USAGE ON WAREHOUSE "SYSTEM$STREAMLIT_NOTEBOOK_WH" TO ROLE TRUST_SIGNAL_PLATFORM_OPERATOR;
GRANT USAGE ON COMPUTE POOL SYSTEM_COMPUTE_POOL_CPU TO ROLE TRUST_SIGNAL_PLATFORM_OPERATOR;
GRANT USAGE ON COMPUTE POOL SYSTEM_COMPUTE_POOL_GPU TO ROLE TRUST_SIGNAL_PLATFORM_OPERATOR;
GRANT ROLE TRUST_SIGNAL_PLATFORM_OPERATOR TO USER ANKURAGARWAL;

-- These revocations are account-wide; other users need explicit replacement roles.
REVOKE USE AI FUNCTIONS ON ACCOUNT FROM ROLE PUBLIC;
REVOKE BIND SERVICE ENDPOINT ON ACCOUNT FROM ROLE PUBLIC;
REVOKE EXECUTE AGENT TASK ON ACCOUNT FROM ROLE PUBLIC;
REVOKE MANAGE ARTIFACT PUBLICATION ON ACCOUNT FROM ROLE PUBLIC;
REVOKE DATABASE ROLE SNOWFLAKE.CORTEX_USER FROM ROLE PUBLIC;
REVOKE DATABASE ROLE SNOWFLAKE.COPILOT_USER FROM ROLE PUBLIC;
-- ML_USER is an irrevocable Snowflake PUBLIC database role; retain it.
-- This DEV account also rejected DATA_METRIC_USER revocation; retain and report it.
REVOKE ROLE SNOWFLAKE_LEARNING_ROLE FROM ROLE PUBLIC;
REVOKE USAGE ON WAREHOUSE "SYSTEM$STREAMLIT_NOTEBOOK_WH" FROM ROLE PUBLIC;
REVOKE USAGE ON COMPUTE POOL SYSTEM_COMPUTE_POOL_CPU FROM ROLE PUBLIC;
REVOKE USAGE ON COMPUTE POOL SYSTEM_COMPUTE_POOL_GPU FROM ROLE PUBLIC;

ALTER USER TRUST_SIGNAL_INGEST_SVC SET DEFAULT_SECONDARY_ROLES = ();

SHOW GRANTS TO ROLE TRUST_SIGNAL_PLATFORM_OPERATOR;
SHOW GRANTS TO ROLE PUBLIC;
SHOW GRANTS TO USER TRUST_SIGNAL_INGEST_SVC;
SHOW TASKS LIKE 'TS_CLAIM' IN SCHEMA TRUST_SIGNAL_DEV.TRUST_SIGNAL_OPS;
