-- Apply with the intended TrustSignal development database selected.
-- Snowflake standard-table uniqueness is enforced by the application, not this DDL.

CREATE SCHEMA IF NOT EXISTS TRUST_SIGNAL_RAW;
CREATE SCHEMA IF NOT EXISTS TRUST_SIGNAL_CORE;
CREATE SCHEMA IF NOT EXISTS TRUST_SIGNAL_OPS;
CREATE SCHEMA IF NOT EXISTS TRUST_SIGNAL_SERVE;

CREATE TABLE IF NOT EXISTS TRUST_SIGNAL_RAW.SOURCE_OBSERVATIONS (
    OBSERVATION_ID       VARCHAR NOT NULL,
    TENANT_ID            VARCHAR,
    SOURCE_ID            VARCHAR NOT NULL,
    SOURCE_RECORD_ID     VARCHAR NOT NULL,
    CASE_ID              VARCHAR,
    CANONICAL_URL        VARCHAR,
    PUBLISHED_AT         TIMESTAMP_TZ,
    OBSERVED_AT          TIMESTAMP_TZ NOT NULL,
    INGESTED_AT          TIMESTAMP_TZ NOT NULL,
    CONTENT_HASH         VARCHAR NOT NULL,
    CONNECTOR_VERSION    VARCHAR NOT NULL,
    PAYLOAD_FORMAT       VARCHAR NOT NULL,
    RAW_PAYLOAD          VARIANT NOT NULL
);

CREATE TABLE IF NOT EXISTS TRUST_SIGNAL_CORE.CASES (
    CASE_ID              VARCHAR NOT NULL,
    TENANT_ID            VARCHAR NOT NULL,
    SCHEMA_VERSION       VARCHAR NOT NULL,
    CASE_VERSION         NUMBER(10, 0) NOT NULL,
    SOURCE_MODE          VARCHAR NOT NULL,
    CASE_STATUS          VARCHAR NOT NULL,
    IDENTITY_STATUS      VARCHAR NOT NULL,
    LEGAL_NAME           VARCHAR NOT NULL,
    JURISDICTION         VARCHAR,
    REGISTRATION_ID      VARCHAR,
    LEI                  VARCHAR,
    REQUESTED_AT         TIMESTAMP_TZ NOT NULL,
    CREATED_AT           TIMESTAMP_TZ NOT NULL,
    UPDATED_AT           TIMESTAMP_TZ NOT NULL
);

CREATE TABLE IF NOT EXISTS TRUST_SIGNAL_CORE.BRANCH_RUNS (
    BRANCH_RUN_ID        VARCHAR NOT NULL,
    CASE_ID              VARCHAR NOT NULL,
    TENANT_ID            VARCHAR NOT NULL,
    BRANCH_ID            VARCHAR NOT NULL,
    ATTEMPT              NUMBER(10, 0) NOT NULL,
    BRANCH_STATUS        VARCHAR NOT NULL,
    STARTED_AT           TIMESTAMP_TZ NOT NULL,
    COMPLETED_AT         TIMESTAMP_TZ,
    RESULT               VARIANT,
    LIMITATIONS          ARRAY,
    ERROR_CATEGORY       VARCHAR
);

CREATE TABLE IF NOT EXISTS TRUST_SIGNAL_CORE.FINDINGS (
    FINDING_ID           VARCHAR NOT NULL,
    CASE_ID              VARCHAR NOT NULL,
    BRANCH_RUN_ID        VARCHAR NOT NULL,
    TENANT_ID            VARCHAR NOT NULL,
    CLAIM_TYPE           VARCHAR NOT NULL,
    CLAIM                VARCHAR NOT NULL,
    SUBJECT              VARCHAR NOT NULL,
    SOURCE_ID            VARCHAR NOT NULL,
    SOURCE_RECORD_ID     VARCHAR,
    CANONICAL_URL        VARCHAR,
    CONTENT_HASH         VARCHAR,
    CONNECTOR_VERSION    VARCHAR,
    OBSERVED_AT          TIMESTAMP_TZ NOT NULL,
    EVENT_AT             TIMESTAMP_TZ,
    EVIDENCE_MODE        VARCHAR NOT NULL,
    VERIFICATION_STATUS  VARCHAR NOT NULL,
    PROCEDURAL_STATUS    VARCHAR,
    RISK_WEIGHT          NUMBER(3, 0) NOT NULL
);

CREATE TABLE IF NOT EXISTS TRUST_SIGNAL_CORE.COMPARISON_ITEMS (
    COMPARISON_ITEM_ID   VARCHAR NOT NULL,
    CASE_ID              VARCHAR NOT NULL,
    TENANT_ID            VARCHAR NOT NULL,
    FINDING_IDS          ARRAY NOT NULL,
    RELATION             VARCHAR NOT NULL,
    SUMMARY              VARCHAR NOT NULL,
    CREATED_AT           TIMESTAMP_TZ NOT NULL
);

CREATE TABLE IF NOT EXISTS TRUST_SIGNAL_CORE.ASSESSMENTS (
    ASSESSMENT_ID        VARCHAR NOT NULL,
    CASE_ID              VARCHAR NOT NULL,
    TENANT_ID            VARCHAR NOT NULL,
    POLICY_VERSION       VARCHAR NOT NULL,
    RISK_SCORE           NUMBER(3, 0),
    SCORE_STATUS         VARCHAR NOT NULL,
    REASONS              ARRAY NOT NULL,
    DISPOSITION          VARCHAR NOT NULL,
    CREATED_AT           TIMESTAMP_TZ NOT NULL
);

CREATE TABLE IF NOT EXISTS TRUST_SIGNAL_CORE.CASE_ACTIONS (
    ACTION_ID            VARCHAR NOT NULL,
    CASE_ID              VARCHAR NOT NULL,
    TENANT_ID            VARCHAR NOT NULL,
    ACTOR_ID             VARCHAR NOT NULL,
    ACTION               VARCHAR NOT NULL,
    RATIONALE            VARCHAR NOT NULL,
    PRIOR_STATUS         VARCHAR NOT NULL,
    NEW_STATUS           VARCHAR NOT NULL,
    CREATED_AT           TIMESTAMP_TZ NOT NULL
);

CREATE TABLE IF NOT EXISTS TRUST_SIGNAL_OPS.SOURCE_RUNS (
    SOURCE_RUN_ID        VARCHAR NOT NULL,
    SOURCE_ID            VARCHAR NOT NULL,
    STARTED_AT           TIMESTAMP_TZ NOT NULL,
    COMPLETED_AT         TIMESTAMP_TZ,
    RUN_STATUS           VARCHAR NOT NULL,
    RECORDS_SEEN         NUMBER(18, 0),
    RECORDS_ACCEPTED     NUMBER(18, 0),
    CONNECTOR_VERSION    VARCHAR NOT NULL,
    ERROR_CATEGORY       VARCHAR,
    DETAILS              VARIANT
);
