-- Case submission, configuration, and analyst-serving objects.
-- Apply after V001 with the TrustSignal development database selected.

CREATE TABLE IF NOT EXISTS TRUST_SIGNAL_CORE.CASE_REQUESTS (
    REQUEST_ID            VARCHAR NOT NULL,
    CASE_ID               VARCHAR NOT NULL,
    TENANT_ID             VARCHAR NOT NULL,
    REQUEST_STATUS        VARCHAR NOT NULL,
    IDEMPOTENCY_KEY       VARCHAR NOT NULL,
    REQUESTED_BY          VARCHAR NOT NULL,
    REQUESTED_AT          TIMESTAMP_TZ NOT NULL,
    CLAIMED_AT            TIMESTAMP_TZ,
    COMPLETED_AT          TIMESTAMP_TZ,
    REQUEST_PAYLOAD       VARIANT NOT NULL,
    ERROR_CATEGORY        VARCHAR,
    ERROR_MESSAGE         VARCHAR
);

CREATE TABLE IF NOT EXISTS TRUST_SIGNAL_CORE.SCORING_POLICIES (
    POLICY_VERSION        VARCHAR NOT NULL,
    EFFECTIVE_FROM        TIMESTAMP_TZ NOT NULL,
    EFFECTIVE_TO          TIMESTAMP_TZ,
    POLICY_STATUS         VARCHAR NOT NULL,
    POLICY_DOCUMENT       VARIANT NOT NULL,
    APPROVED_BY           VARCHAR,
    APPROVED_AT           TIMESTAMP_TZ,
    CREATED_AT            TIMESTAMP_TZ NOT NULL
);

CREATE TABLE IF NOT EXISTS TRUST_SIGNAL_OPS.SOURCE_CATALOG (
    SOURCE_ID                 VARCHAR NOT NULL,
    SOURCE_NAME               VARCHAR NOT NULL,
    SOURCE_CLASS              VARCHAR NOT NULL,
    JURISDICTIONS             ARRAY NOT NULL,
    ACCESS_METHOD             VARCHAR NOT NULL,
    STATUS                    VARCHAR NOT NULL,
    EXPECTED_FRESHNESS_MINUTES NUMBER(12, 0),
    TERMS_REVIEWED_AT          TIMESTAMP_TZ,
    OWNER                      VARCHAR NOT NULL,
    CONNECTOR_VERSION          VARCHAR,
    NOTES                      VARCHAR,
    UPDATED_AT                 TIMESTAMP_TZ NOT NULL
);

CREATE OR REPLACE VIEW TRUST_SIGNAL_SERVE.V_CASE_SUMMARY AS
SELECT
    c.CASE_ID,
    c.TENANT_ID,
    c.CASE_STATUS,
    c.IDENTITY_STATUS,
    c.LEGAL_NAME,
    c.JURISDICTION,
    c.REGISTRATION_ID,
    c.LEI,
    c.REQUESTED_AT,
    c.UPDATED_AT,
    a.POLICY_VERSION,
    a.RISK_SCORE,
    a.SCORE_STATUS,
    a.DISPOSITION,
    a.REASONS AS ASSESSMENT_REASONS
FROM TRUST_SIGNAL_CORE.CASES AS c
LEFT JOIN (
    SELECT *
    FROM TRUST_SIGNAL_CORE.ASSESSMENTS
    QUALIFY ROW_NUMBER() OVER (PARTITION BY TENANT_ID, CASE_ID ORDER BY CREATED_AT DESC) = 1
) AS a ON c.CASE_ID = a.CASE_ID AND c.TENANT_ID = a.TENANT_ID;

CREATE OR REPLACE VIEW TRUST_SIGNAL_SERVE.V_CASE_FINDINGS AS
SELECT
    f.CASE_ID,
    f.TENANT_ID,
    f.FINDING_ID,
    f.BRANCH_RUN_ID,
    f.CLAIM_TYPE,
    f.CLAIM,
    f.SUBJECT,
    f.SOURCE_ID,
    f.SOURCE_RECORD_ID,
    f.CANONICAL_URL,
    f.OBSERVED_AT,
    f.EVENT_AT,
    f.EVIDENCE_MODE,
    f.VERIFICATION_STATUS,
    f.PROCEDURAL_STATUS,
    f.RISK_WEIGHT,
    b.BRANCH_ID,
    b.BRANCH_STATUS,
    b.LIMITATIONS
FROM TRUST_SIGNAL_CORE.FINDINGS AS f
JOIN TRUST_SIGNAL_CORE.BRANCH_RUNS AS b
  ON f.BRANCH_RUN_ID = b.BRANCH_RUN_ID
 AND f.CASE_ID = b.CASE_ID
 AND f.TENANT_ID = b.TENANT_ID;

CREATE OR REPLACE VIEW TRUST_SIGNAL_SERVE.V_SOURCE_HEALTH AS
SELECT
    c.SOURCE_ID,
    c.SOURCE_NAME,
    c.SOURCE_CLASS,
    c.JURISDICTIONS,
    c.ACCESS_METHOD,
    c.STATUS AS CATALOG_STATUS,
    c.EXPECTED_FRESHNESS_MINUTES,
    r.RUN_STATUS AS LAST_RUN_STATUS,
    r.STARTED_AT AS LAST_RUN_STARTED_AT,
    r.COMPLETED_AT AS LAST_RUN_COMPLETED_AT,
    r.ERROR_CATEGORY AS LAST_ERROR_CATEGORY,
    DATEDIFF('minute', r.COMPLETED_AT, CURRENT_TIMESTAMP()) AS MINUTES_SINCE_LAST_RUN
FROM TRUST_SIGNAL_OPS.SOURCE_CATALOG AS c
LEFT JOIN (
    SELECT *
    FROM TRUST_SIGNAL_OPS.SOURCE_RUNS
    QUALIFY ROW_NUMBER() OVER (PARTITION BY SOURCE_ID ORDER BY STARTED_AT DESC) = 1
) AS r ON c.SOURCE_ID = r.SOURCE_ID;
