-- Apply independently after the database and TRUST_SIGNAL_OPS schema exist.
CREATE TABLE IF NOT EXISTS TRUST_SIGNAL_OPS.SOURCE_RUNS (
    SOURCE_RUN_ID VARCHAR NOT NULL,
    SOURCE_ID VARCHAR NOT NULL,
    STARTED_AT TIMESTAMP_TZ NOT NULL,
    COMPLETED_AT TIMESTAMP_TZ,
    RUN_STATUS VARCHAR NOT NULL,
    RECORDS_SEEN NUMBER(18,0),
    RECORDS_ACCEPTED NUMBER(18,0),
    CONNECTOR_VERSION VARCHAR NOT NULL,
    ERROR_CATEGORY VARCHAR,
    DETAILS VARIANT
);
