-- Identity decisions are immutable snapshots, including input, candidates and provenance.
-- The application enforces sequential replay; standard tables do not enforce uniqueness.
CREATE TABLE IF NOT EXISTS TRUST_SIGNAL_CORE.IDENTITY_DECISIONS (
    IDENTITY_DECISION_ID VARCHAR NOT NULL,
    TENANT_ID VARCHAR NOT NULL,
    CASE_ID VARCHAR NOT NULL,
    INPUT_VERSION NUMBER(10, 0) NOT NULL,
    POLICY_VERSION VARCHAR NOT NULL,
    RESOLUTION_STATUS VARCHAR NOT NULL,
    RESEARCH VARIANT NOT NULL,
    CREATED_AT TIMESTAMP_TZ NOT NULL
);

CREATE VIEW IF NOT EXISTS TRUST_SIGNAL_SERVE.V_IDENTITY_CANDIDATES AS
SELECT d.IDENTITY_DECISION_ID, d.TENANT_ID, d.CASE_ID, d.INPUT_VERSION,
       d.POLICY_VERSION, d.RESOLUTION_STATUS,
       m.value:candidate:candidate_id::VARCHAR AS CANDIDATE_ID,
       m.value:candidate AS CANDIDATE,
       m.value:status::VARCHAR AS MATCH_STATUS,
       m.value:reason_codes AS REASON_CODES,
       m.value:eligible_for_attribution::BOOLEAN AS ELIGIBLE_FOR_ATTRIBUTION
FROM TRUST_SIGNAL_CORE.IDENTITY_DECISIONS d,
     LATERAL FLATTEN(INPUT => d.RESEARCH:resolution:matches) m;

CREATE VIEW IF NOT EXISTS TRUST_SIGNAL_SERVE.V_IDENTITY_EVIDENCE AS
SELECT d.IDENTITY_DECISION_ID, d.TENANT_ID, d.CASE_ID, d.INPUT_VERSION,
       e.value:evidence_id::VARCHAR AS EVIDENCE_ID,
       e.value:observation_id::VARCHAR AS OBSERVATION_ID,
       e.value:subject_candidate_id::VARCHAR AS CANDIDATE_ID,
       e.value AS EVIDENCE
FROM TRUST_SIGNAL_CORE.IDENTITY_DECISIONS d,
     LATERAL FLATTEN(INPUT => d.RESEARCH:evidence) e;
