ALTER TABLE TRUST_SIGNAL_RAW.SOURCE_OBSERVATIONS
    ADD COLUMN IF NOT EXISTS RAW_CHUNK_COUNT NUMBER(10, 0) DEFAULT 0;

CREATE TABLE IF NOT EXISTS TRUST_SIGNAL_RAW.SOURCE_RESPONSE_CHUNKS (
    OBSERVATION_ID VARCHAR NOT NULL,
    CHUNK_INDEX NUMBER(10, 0) NOT NULL,
    RAW_BYTES_BASE64 VARCHAR NOT NULL,
    CHUNK_HASH VARCHAR NOT NULL
);
-- Grant SELECT/INSERT on the new table to the configured runtime role.
