-- Durable execution state. Deploy procedures/tasks separately; this DDL starts no compute.
-- One non-overlapping graph owns claims; each stage has a single writer per run.
CREATE TABLE IF NOT EXISTS TRUST_SIGNAL_OPS.CASE_RUNS (
    RUN_ID VARCHAR NOT NULL,
    GRAPH_RUN_ID VARCHAR NOT NULL,
    REQUEST_ID VARCHAR NOT NULL,
    CASE_ID VARCHAR NOT NULL,
    TENANT_ID VARCHAR NOT NULL,
    RUN_STATUS VARCHAR NOT NULL,
    REQUEST_PAYLOAD VARIANT NOT NULL,
    RESULT VARIANT,
    ERROR_CATEGORY VARCHAR,
    STARTED_AT TIMESTAMP_TZ NOT NULL,
    COMPLETED_AT TIMESTAMP_TZ
);

CREATE TABLE IF NOT EXISTS TRUST_SIGNAL_OPS.STAGE_ATTEMPTS (
    ATTEMPT_ID VARCHAR NOT NULL,
    RUN_ID VARCHAR NOT NULL,
    STAGE VARCHAR NOT NULL,
    ATTEMPT NUMBER(10, 0) NOT NULL,
    STAGE_STATUS VARCHAR NOT NULL,
    OUTPUT VARIANT,
    ERROR_CATEGORY VARCHAR,
    STARTED_AT TIMESTAMP_TZ NOT NULL,
    COMPLETED_AT TIMESTAMP_TZ
);

CREATE STAGE IF NOT EXISTS TRUST_SIGNAL_OPS.WORKFLOW_CODE;

CREATE VIEW IF NOT EXISTS TRUST_SIGNAL_SERVE.V_WORKFLOW_RESULTS AS
SELECT RUN_ID, GRAPH_RUN_ID, REQUEST_ID, CASE_ID, TENANT_ID, RUN_STATUS,
       RESULT, ERROR_CATEGORY, STARTED_AT, COMPLETED_AT
FROM TRUST_SIGNAL_OPS.CASE_RUNS;

CREATE VIEW IF NOT EXISTS TRUST_SIGNAL_SERVE.V_WORKFLOW_PROGRESS AS
SELECT r.RUN_ID, r.CASE_ID, r.TENANT_ID, r.RUN_STATUS,
       s.STAGE, s.ATTEMPT, s.STAGE_STATUS, s.ERROR_CATEGORY,
       s.STARTED_AT, s.COMPLETED_AT
FROM TRUST_SIGNAL_OPS.CASE_RUNS r
JOIN TRUST_SIGNAL_OPS.STAGE_ATTEMPTS s ON r.RUN_ID = s.RUN_ID
QUALIFY ROW_NUMBER() OVER (PARTITION BY s.RUN_ID, s.STAGE ORDER BY s.ATTEMPT DESC) = 1;
